services:
  api:
    build: .
    command: node server.js
    ports:
      - "5001:5000"
    environment:
      - SERVICE_NAME=api
    env_file: .env
    volumes:
      - /home/deploy/growthinfi/bulk-calendarInvites/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis

  scheduler:
    build: .
    command: node scheduler.js
    environment:
      - SERVICE_NAME=scheduler
    env_file: .env
    volumes:
      - /home/deploy/growthinfi/bulk-calendarInvites/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis

  worker:
    build: .
    command: node workers/email.worker.js
    env_file: .env
    environment:
      - SERVICE_NAME=worker
    volumes:
      - /home/deploy/growthinfi/bulk-calendarInvites/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
